/* Auto-generated by build script, do not edit */

#define HAVE_STDIO_H 1
#include <stdio.h>

#define HAVE_UNISTD_H 1
#include <unistd.h>

#define HAVE_SYS_WAIT_H 1
#include <sys/wait.h>

#define HAVE_SIGNAL_H 1
#include <signal.h>

#define HAVE_STDLIB_H 1
#include <stdlib.h>

#define HAVE_SETENV 1

