import os, glob

Import('env')

sources = Split("""
dispatcher_factory.cpp
""")

sources.extend(glob.glob('*_dispatcher.h'))

os.popen("./gen_factory.pl")

#env.GenerateDispatchFactory('', '')
env.StaticLibrary(target = 'dispatch', source = sources)

# vim: ft=python
