import os, glob

Import('env')

sources = Split("""
dispatcher_factory.cpp
event_state.cpp
""")

sources.extend(glob.glob('*_dispatcher.cpp'))
os.popen("./gen_factory.pl")

print sources
env.StaticLibrary(target = 'dispatch', source = sources)

# vim: ft=python
